import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, readdir, stat, writeFile, copyFile, rm } from 'node:fs/promises';
import path from 'node:path';
async function walk(folder) { const out = []; for (const entry of await readdir(folder, { withFileTypes: true })) { const p = path.join(folder, entry.name); if (entry.isDirectory()) out.push(...await walk(p)); else if (entry.isFile()) out.push(p); } return out; }
async function sha256(file) { return createHash('sha256').update(await readFile(file)).digest('hex'); }
export class SelectionStage { name = 'Selection'; async run(ctx) { ctx.logs.user.push('Sélection des dossiers à protéger.'); ctx.selectedFiles = []; for (const folder of ctx.configuration.folders.filter(f => f.included)) for (const file of await walk(folder.path)) { const s = await stat(file); ctx.selectedFiles.push({ sourcePath: file, relativePath: path.relative(folder.path, file), size: s.size, modifiedAt: s.mtime.toISOString(), hash: await sha256(file) }); } return ctx; } }
export class PreparationStage { name = 'Preparation'; async run(ctx) { await mkdir(ctx.workingDirectory, { recursive: true }); ctx.logs.user.push(`${ctx.selectedFiles.length} fichier(s) prêts pour la sauvegarde.`); return ctx; } }
export class RftPackageStage { name = 'Optimization'; async run(ctx) { const manifest = { format: 'rft-backup-package', version: 1, createdAt: new Date().toISOString(), files: ctx.selectedFiles }; const body = JSON.stringify(manifest, null, 2); ctx.packagePath = path.join(ctx.workingDirectory, `${ctx.configuration.id}-${Date.now()}.rftpkg`); await writeFile(ctx.packagePath, body); ctx.packageHash = createHash('sha256').update(body).digest('hex'); ctx.logs.technical.push(`Package ${ctx.packagePath} hash=${ctx.packageHash}`); return ctx; } }
export class LocalSftpTransferStage { name = 'Transfer'; async run(ctx) { if (!ctx.packagePath) throw new Error('Package missing'); await mkdir(ctx.configuration.destination.remotePath, { recursive: true }); ctx.remotePackagePath = path.join(ctx.configuration.destination.remotePath, path.basename(ctx.packagePath)); await copyFile(ctx.packagePath, ctx.remotePackagePath); ctx.logs.user.push('Sauvegarde envoyée vers la destination SFTP.'); return ctx; } }
export class ValidationStage { name = 'Validation'; async run(ctx) { const remoteHash = await sha256(ctx.remotePackagePath); if (remoteHash !== ctx.packageHash) throw new Error('Integrity hash mismatch after transfer'); ctx.logs.user.push('Intégrité validée après transfert.'); return ctx; } }
export class VersionManagementStage { name = 'Version Management'; async run(ctx) { const versions = (await readdir(ctx.configuration.destination.remotePath)).filter(f => f.endsWith('.rftpkg')).sort().reverse(); for (const old of versions.slice(ctx.configuration.retention.count)) await rm(path.join(ctx.configuration.destination.remotePath, old)); ctx.logs.user.push(`Rétention appliquée: conserver les ${ctx.configuration.retention.count} dernières versions.`); return ctx; } }
export class CatalogStage { name = 'Catalog'; async run(ctx) { ctx.version = { id: randomUUID(), configurationId: ctx.configuration.id, createdAt: new Date().toISOString(), fileCount: ctx.selectedFiles.length, totalBytes: ctx.selectedFiles.reduce((a, f) => a + f.size, 0), manifestHash: ctx.packageHash, remotePath: ctx.remotePackagePath }; return ctx; } }
